package model;

import java.util.List;

import annotation.AutoGenerated;
import annotation.FieldName;
import annotation.HasMany;
import annotation.Id;

public class Person implements Entity{
	@Id		
	@AutoGenerated
	@FieldName("id_person")	
	private int id;
	private String name;
	private int age;
	@HasMany
	private List<Car> cars;
	
	public Person(int id, String name, int age) {
		this.id = id;
		this.name = name;
		this.age = age;
	}
}